# Generated by Django 2.0.8 on 2020-06-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_annotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='annotation',
            field=models.TextField(default='', max_length=300),
        ),
    ]
